# Generated by Django 4.2.17 on 2024-12-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_customer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='connection_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.AddField(
            model_name='customer',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='installation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='installation_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (1 PM - 4 PM)'), ('evening', 'Evening (4 PM - 7 PM)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.cableplan'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disconnected', 'Disconnected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
